# Generated by Django 5.2.3 on 2025-06-22 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('ordem', models.PositiveIntegerField(unique=True)),
                ('idade_minima', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graus', to='core.faixa')),
            ],
            options={
                'unique_together': {('faixa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(choices=[('ALUNO', 'Aluno'), ('PENDENTE', 'Professor Pendente'), ('PROFESSOR', 'Professor Aprovado')], default='ALUNO', max_length=10)),
                ('faixa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.faixa')),
                ('grau_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('grau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='core.grau')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url_video', models.URLField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='core.topico')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tecnica')),
            ],
            options={
                'unique_together': {('perfil', 'tecnica')},
            },
        ),
    ]
