# Generated by Django 5.2.3 on 2025-06-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grau',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grau',
            name='publico_alvo',
            field=models.CharField(choices=[('INFANTIL', 'Infantil (até 15 anos)'), ('ADULTO', 'Adulto (16 anos ou mais)')], default='ADULTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='grau_atual',
            field=models.ForeignKey(blank=True, help_text='Grau atual do aluno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grau'),
        ),
        migrations.AlterUniqueTogether(
            name='grau',
            unique_together={('faixa', 'numero', 'publico_alvo')},
        ),
    ]
