# Generated by Django 5.2.3 on 2025-06-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_popular_dados_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grau',
            name='faixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graus', to='core.faixa', verbose_name='Faixa'),
        ),
        migrations.AlterField(
            model_name='grau',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Grau'),
        ),
        migrations.AlterField(
            model_name='grau',
            name='titulo',
            field=models.CharField(help_text='Ex: Fundamentos da Postura e Mobilidade', max_length=200),
        ),
    ]
