# Generated by Django 5.2.3 on 2025-06-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grau_faixa_alter_grau_numero_alter_grau_titulo'),
        ('core', '0005_criar_superuser'),
    ]

    operations = [
    ]
