"""
Django settings for jitsu_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jt#-c3m%6)s*zm3-_*p-w88dn#rj07lkytqo3rykz7es8+uq&p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'jitsu-performance-site.onrender.com',
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Adicione esta linha
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # A nossa app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jitsu_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jitsu_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Em jitsu_project/settings.py

STATIC_URL = 'static/'

# ---- ADICIONE ESTAS LINHAS ----
# O local onde o collectstatic irá reunir todos os ficheiros para produção
STATIC_ROOT = BASE_DIR / 'staticfiles'

# A configuração para o WhiteNoise servir os ficheiros estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# -------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# No final do ficheiro settings.py

JAZZMIN_SETTINGS = {
    # Título da janela do navegador (pode usar o nome do seu site)
    "site_title": "JitsuPerformance Admin",

    # Título no topo da página de login e do painel
    "site_header": "JitsuPerformance",

    # Texto que aparece no topo, ao lado do logo
    "site_brand": "JitsuPerformance",

    # Caminho para um logo (opcional, vamos configurar mais tarde se quiser)
    # "site_logo": "caminho/para/seu/logo.png",

    # Mensagem de boas-vindas na tela de login
    "welcome_sign": "Bem-vindo ao painel de administração da JitsuPerformance",

    # Copyright no rodapé
    "copyright": "JitsuPerformance Ltd.",

    # Links que aparecem no menu superior
    "topmenu_links": [
        # Link para a "home" do admin
        {"name": "Home", "url": "admin:index"},
        # Link para o seu site principal (que ainda vamos construir)
        {"name": "Ver o Site", "url": "/", "new_window": True},
        # Modelo de um link externo
        {"model": "auth.User", "name": "Usuários"},
    ],
}
LOGIN_URL = 'homepage' 

# No final de settings.py

# Faz com que a sessão do usuário (o login) expire quando o navegador for fechado
SESSION_EXPIRE_AT_BROWSER_CLOSE = True